projectlion/liongram/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import index, url_view, url_parameter_view, function_view, class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view(), name = 'cbv'),    # class라서 .as_view() 필수
    path('', index, name='index'),
    path('posts/', include('posts.urls', namespace = 'posts')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectlion/liongram/posts/urls.py
from django.urls import path

from .views import post_list_view, post_create_view, post_update_view, post_detail_view, post_delete_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name = 'post-list'),
    path('create/', post_create_view, name='post-create'),
    path('<int:id>/',post_detail_view),
    path('<int:id>/edit/',post_update_view ),
    path('<int:id>/delete/',post_delete_view),
]

projectlion/liongram/posts/forms.py
from django import forms


class PostBaseForm(forms.Form):
    image = forms.ImageField()
    content = forms.CharField(widget=forms.Textarea)

projectlion/liongram/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView

from .forms import PostBaseForm
from .models import Post
# Create your views here.
def index(request):
    return render(request, 'index.html')

def post_list_view(request):
    # post_list = Post.objects.all()    # Post 전체 데이터 조회
    post_list = Post.objects.filter(writer=request.user)    # Post.writer가 현재 로그인인 것 조회
    context = {
        'post_list': post_list,
    }
    return render(request, 'posts/post_list.html', context)

def post_detail_view(request, id):
    return render(request, 'posts/post_detail.html')

@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')

        Post.objects.create(
            image=image,
            content=content,
            writer=request.user,
        )

        return redirect('index')


@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html', {'form': PostBaseForm()})
    else:
        form = PostBaseForm(request.POST, request.FILES)

        if form.is_valid():
            Post.objects.create(
                image=form.cleaned_data.get('image'),
                content=form.cleaned_data.get('content'),
                writer=request.user,
            )
        else:
            return redirect('posts:post-create')

        return redirect('index')

def post_update_view(request, id):
    return render(request, 'posts/post_form.html')

def post_delete_view(request, id):
    return render(request, 'posts/post_confirm_delete.html')

def url_view(request):  
    print('url_view()') # 터미널 창에 찍히는 것 확인
    data = {'code' : '001', 'msg' : 'OK'}
    return HttpResponse('<h1>url_view</h1>')    # html이 기본
    # return JsonResponse(data)

def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username:{username}')
    print(f'request.GET:{request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method: {request.method}')

    if request.method == 'GET':
        print(f'request.GET:{request.GET}')
    elif request.method == 'POST':
        print(f'request.Post: {request.POST}')
    return render(request, 'view.html')

class class_view(ListView):
    model = Post
    ordering = ['-id']
    template_name = 'cbv_view.html'

def function_list_view(request):
    object_list = Post.objects.all().order_by('-id')
    return render(request, 'cbv_view.html', {object_list: object_list})

projectlion/liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css'%}">
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <nav>
            <ul class="bottom-menu-group">
                <li>
                    <img src="{% static 'icons/home_outlined_black_36dp.svg' %}", alt="홈">
                </li>
                <li>
                    <img src="{% static 'icons/search_outlined_black_36dp.svg' %}", alt="검색"/>
                </li>
                <li>
                    <a href="{% url 'posts:post-create'%}">
                        <img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}", alt="글쓰기"/>
                    </a>
                </li>
                <li>
                    <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}", alt="좋아요"/>
                </li>
                <li>
                    <img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}", alt="프로필"/>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

projectlion/liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}홈{% endblock %}

{% block content %}
<main>
    <div class="card-list">
        {% include 'mixin/posts/post_card.html' %}
    </div>
</main>
{% endblock %}

projectlion/liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card_header">
        <img src="http://via.placeholder.com/32x32" alt="프로필이미지">
        <a href="#">
            <span class="card__user-name">likelion.official</span>
        </a>
    </div>
    <div class="card__body">
        <div>
            <image class="card__image" src="http://via.placeholder.com/600x600" alt="">
        </div>
        <div class="card__btn-group">
            </div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg'%}" alt="좋아요">
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg'%}" alt="댓글">
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg'%}" alt="공유하기">
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg'%}" alt="북마크">
            </div>
        </div>
        <div class="card_content">
            <span class="card__like-num">좋아요 00개</span>
            <div class="card__main-text">
                <p><span class="card__user-name">likelion.official</span>{{"실무와 현업에서 필요로 하는 백엔드 개발자로의 역량 배양에 효과적..."|truncatechars:35}} 더보기</p>
            </div>
            <div>
                <p>댓글 0개 모두 보기</p>
                <ul class="card_comment-group">
                    <li>
                        <p><span class="card__user-name">likelion.official</span>댓글 내용...</p>
                    </li>
                </ul>
                <p class="card_created-at">2023년 5월 10일</p>
            </div>
        </div>
    </div>
</div>

projectlion/liongram/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}글 삭제{% endblock %}

{% block content %}
<h1>Post 삭제 화면</h1>
{% endblock %}

projectlion/liongram/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}글 상세{% endblock %}

{% block content %}
<h1>Post 상세 화면</h1>
{% include 'mixin/posts/post_card.html'%}
{% endblock %}

projectlion/liongram/templates/posts/post_form.html
{% extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
<h1>Post 입력 화면</h1>
<form action="{% url 'posts:post-create'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token%} 
    <div>
        <label for="id_image">이미지</label>
        <input type="file" name="image" accept="image/*" id="id_image">
    </div>
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" cols="30" rows="10"></textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

projectlion/liongram/templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}

{% block content %}
<h1>Post 목록 화면</h1>
<!-- {{post_list}} -->

{% for post in post_list %}
    <div>
        {{post.id}}<br/>
        {{post.image}}<br/>
        {{post.content}}<br/>
        {{post.created_at}}<br/>
        {{post.writer}}<br/>
    </div>
{% endfor %}
{% endblock %}